"""cursor positions table

Revision ID: 028d2a9ed8ac
Revises: e4e8b52dc648
Create Date: 2022-04-12 10:17:09.987974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '028d2a9ed8ac'
down_revision = 'e4e8b52dc648'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cursor_position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('since_id', sa.Integer(), nullable=True),
    sa.Column('key_word', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cursor_position')
    # ### end Alembic commands ###
