"""tweets id added

Revision ID: e4e8b52dc648
Revises: 
Create Date: 2022-04-11 09:55:12.430181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4e8b52dc648'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tweets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=280), nullable=True),
    sa.Column('hash_tag', sa.String(length=64), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('tweet_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tweets_body'), 'tweets', ['body'], unique=False)
    op.create_index(op.f('ix_tweets_date_created'), 'tweets', ['date_created'], unique=False)
    op.create_index(op.f('ix_tweets_hash_tag'), 'tweets', ['hash_tag'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tweets_hash_tag'), table_name='tweets')
    op.drop_index(op.f('ix_tweets_date_created'), table_name='tweets')
    op.drop_index(op.f('ix_tweets_body'), table_name='tweets')
    op.drop_table('tweets')
    # ### end Alembic commands ###
